services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=jack
      - POSTGRES_PASSWORD=abcdef
      - POSTGRES_DATABASE=denim_test
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata: